import { useState, type FormEvent } from 'react'
import { ApiError } from '../../api/client'
import { useAuth } from '../../auth/useAuth'

export function LoginPage() {
  const { login } = useAuth(); const [companyId, setCompanyId] = useState(''); const [userName, setUserName] = useState(''); const [password, setPassword] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const id = Number(companyId); if (!Number.isInteger(id) || id <= 0) { setError('Informe um código de empresa válido.'); return }; setError(''); setIsSubmitting(true); try { await login({ companyId: id, userName: userName.trim(), password }) } catch (requestError) { setError(getLoginMessage(requestError)) } finally { setIsSubmitting(false) } }
  return <main className="login-page"><section className="login-introduction" aria-labelledby="login-title"><a className="brand" href="/login"><span className="brand-mark" aria-hidden="true">L</span><span>Loyalty Platform</span></a><div><p className="eyebrow">Administração de fidelidade</p><h1 id="login-title">Tudo para cuidar de relações que voltam.</h1><p className="login-description">Acesse o ambiente da sua empresa com segurança e acompanhe o que importa para o seu programa.</p></div></section><section className="login-panel" aria-labelledby="login-form-title"><form className="login-form" onSubmit={submit} noValidate><div><p className="eyebrow">Acesso administrativo</p><h2 id="login-form-title">Entre na sua conta</h2><p className="form-description">Use as credenciais fornecidas pela sua empresa.</p></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-field"><label htmlFor="companyId">Código da empresa</label><input id="companyId" type="number" inputMode="numeric" min="1" autoComplete="organization" value={companyId} onChange={(event) => setCompanyId(event.target.value)} disabled={isSubmitting} required /></div><div className="form-field"><label htmlFor="userName">Usuário</label><input id="userName" type="text" autoComplete="username" value={userName} onChange={(event) => setUserName(event.target.value)} disabled={isSubmitting} required /></div><div className="form-field"><label htmlFor="password">Senha</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={isSubmitting} required /></div><button className="primary-button" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Autenticando…' : 'Entrar'}</button></form></section></main>
}
function getLoginMessage(error: unknown) { if (error instanceof ApiError) { if (error.status === 401) return 'Usuário ou senha não conferem. Revise os dados e tente novamente.'; if (error.status === 403) return 'Seu usuário não possui acesso a esta empresa.'; if (error.status === 400) return 'Revise os dados informados e tente novamente.' } return 'Não foi possível realizar o acesso agora. Verifique sua conexão e tente novamente.' }
